org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
android.useAndroidX=false
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
org.gradle.java.installations.paths=/opt/jdk17,/opt/jdk21
org.gradle.java.installations.auto-download=false
